const nodes = [
    { id: 1, name: 'Nodo', status: 'Online', computers: 11, rota:1 },
    { id: 2, name: 'Informatica', status: 'Online', computers: 4, rota:1  },
    { id: 3, name: 'OCID', status: 'Online', computers: 1, rota:0 },
    { id: 4, name: 'Organizacion', status: 'Online', computers: 1, rota:0 },
    { id: 5, name: 'Dirección', status: 'Online', computers: 1, rota:0 },
    { id:6, name: 'Dpto Colaboracion', status: 'Online', computers: 1, rota:0 },
    { id: 7, name: 'V. Técnica', status: 'Online', computers: 1, rota:0 },
    { id: 8, name: 'Dpto Imagen Mamografia', status: 'Online', computers: 1, rota:0 },
    { id: 9, name: 'Dpto Imagen Local de Informe', status: 'Online', computers: 5, rota:1 },
    { id: 10, name: 'Dpto Imagen TAC', status: 'Online', computers: 2, rota:0 },
    { id: 11, name: 'Dpto Imagen RXD', status: 'Online', computers: 1, rota:0 },
    { id: 12, name: 'R. Humano', status: 'Online', computers: 2, rota:0 },
    { id: 13, name: 'Abastecimiento', status: 'Online', computers: 1, rota:1 },
    { id: 14, name: 'Enfermería', status: 'Online', computers: 1, rota:0 },
    { id: 15, name: 'Clinico Quirurgico', status: 'Online', computers: 1, rota:0 },
    { id: 16, name: 'Seg Protección', status: 'Online', computers: 1, rota:0 },
    { id: 17, name: 'Dpto Docencia ', status: 'Online', computers: 1, rota:0 },
    { id: 18, name: 'Dpto. Dietetica', status: 'Online', computers: 1, rota:1 },
    { id: 19, name: 'Dpto. Electromed', status: 'Online', computers: 1, rota:0 },
    { id: 20, name: 'Banco Leche ', status: 'Online', computers: 1, rota:1 },
    { id: 21, name: 'Cuadro', status: 'Online', computers: 1, rota:0 },
    { id: 22, name: 'Biblioteca', status: 'Online', computers: 2, rota:1 },
    { id: 23, name: 'Economía 1', status: 'Online', computers: 8, rota:0},
    { id: 24, name: 'Abastecimiento 1', status: 'Online', computers: 1, rota:1 },
    { id: 25, name: 'Laboratorio Central', status: 'Online', computers: 2, rota:0 },
    { id: 26, name: 'Juridicos', status: 'Online', computers: 1, rota:0 },
    { id: 27, name: 'Administración', status: 'Online', computers: 1, rota:0 },
    { id: 28, name: 'Telefonia', status: 'Online', computers: 3, rota:1 },
    { id: 29, name: 'Estadistica Incripciones ', status: 'Online', computers: 1, rota:0 },
    { id: 30, name: 'Estadistica Jefe Dpto', status: 'Online', computers: 1, rota:0 },
    { id: 31, name: 'Estadistica Registros Quirurgico', status: 'Online', computers: 2, rota:0 },
    { id: 32, name: 'Estadistica Admision ', status: 'Online', computers: 1, rota:0 },
    { id: 33, name: 'Estadistica Certificados', status: 'Online', computers: 2, rota:0 },
    { id: 34, name: 'Ate Población', status: 'Online', computers: 1, rota:0 },
    { id: 35, name: 'Farmacia Interna', status: 'Online', computers: 1, rota:0 },
    { id: 36, name: 'Suma', status: 'Online', computers: 3, rota:2 },
    { id: 37, name: 'Almacen Farmacia', status: 'Online', computers: 1, rota:0 },
    { id: 38, name: 'Medicina Legal ', status: 'Online', computers: 1, rota:0 },
    { id: 39, name: 'Turismo de Salud ', status: 'Online', computers: 2, rota:1 },
    { id: 40, name: 'Quimoterapia Oncologia', status: 'Online', computers: 1, rota:0 },
    { id: 41, name: 'Ensayos Clinicos', status: 'Online', computers: 1, rota:0 },
    { id: 42, name: 'Anat Patologica', status: 'Online', computers: 1, rota:0 },
    { id: 43, name: 'Anat Pato Laptop', status: 'Online', computers: 1, rota:1 },
    { id: 44, name: 'Colaboracion', status: 'Online', computers: 1, rota:0},
    { id: 45, name: 'Oftamologia ', status: 'Online', computers: 5, rota:0 },
    { id: 46, name: 'Endocrino', status: 'Online', computers: 1, rota:0 },
    { id: 47, name: 'Medicina Nuclear', status: 'Online', computers: 1, rota:0 },
    { id: 48, name: 'B-2', status: 'Online', computers: 1, rota:0 },
    { id: 49, name: 'VD Materna', status: 'Online', computers: 0, rota:0 },
    { id: 50, name: 'Neumología  ', status: 'Online', computers: 1, rota:0 },
    { id: 51, name: 'Sala Intensiva  ', status: 'Online', computers: 1, rota:1 },
    { id: 52, name: 'Neurofisiologia   ', status: 'Online', computers: 2, rota:1 },
    { id: 53, name: 'Salón Anestesia    ', status: 'Online', computers: 1, rota:0 },
    { id: 54, name: 'Nefrologia   ', status: 'Offline', computers: 0, rota:0 },
    { id: 54, name: 'Dermatología   ', status: 'Offline', computers: 0, rota:0 },
  ];

  export default nodes;